import {
  FaReact,
  FaNodeJs,
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaBootstrap,
  FaGitAlt,
  FaGithub,
  FaPython,
  FaJava,
  FaDocker,
  FaAws,
  FaFigma,
} from "react-icons/fa";

import {
  SiExpress,
  SiMongodb,
  SiMysql,
  SiPhp,
  SiTailwindcss,
  SiRedux,
  SiNextdotjs,
  SiTypescript,
  SiFirebase,
  SiPostman,
  SiVite,
} from "react-icons/si";

export const skillIcons = {
  react: FaReact,
  node: FaNodeJs,
  "node.js": FaNodeJs,
  express: SiExpress,
  "express.js": SiExpress,
  mongodb: SiMongodb,
  html: FaHtml5,
  html5: FaHtml5,
  css: FaCss3Alt,
  css3: FaCss3Alt,
  javascript: FaJs,
  typescript: SiTypescript,
  bootstrap: FaBootstrap,
  tailwind: SiTailwindcss,
  "tailwind css": SiTailwindcss,
  redux: SiRedux,
  "next.js": SiNextdotjs,
  mysql: SiMysql,
  php: SiPhp,
  git: FaGitAlt,
  github: FaGithub,
  firebase: SiFirebase,
  postman: SiPostman,
  vite: SiVite,
  docker: FaDocker,
  aws: FaAws,
  figma: FaFigma,
  python: FaPython,
  java: FaJava,
};